// ignore_for_file: experimental_member_use
// just_audio marks StreamAudioSource experimental; it is the supported way to
// play generated bytes on every platform including web.
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:just_audio/just_audio.dart';

import 'noise_generator.dart';

enum AmbientSound { off, white, pink, brown }

extension AmbientSoundLabel on AmbientSound {
  String get label => switch (this) {
    AmbientSound.off => 'Off',
    AmbientSound.white => 'White',
    AmbientSound.pink => 'Pink',
    AmbientSound.brown => 'Brown',
  };
}

@immutable
class AmbientAudioState {
  const AmbientAudioState({
    this.sound = AmbientSound.off,
    this.isPlaying = false,
    this.volume = 0.6,
    this.errorMessage,
  });

  final AmbientSound sound;
  final bool isPlaying;
  final double volume;
  final String? errorMessage;

  AmbientAudioState copyWith({
    AmbientSound? sound,
    bool? isPlaying,
    double? volume,
    String? errorMessage,
    bool clearError = false,
  }) => AmbientAudioState(
    sound: sound ?? this.sound,
    isPlaying: isPlaying ?? this.isPlaying,
    volume: volume ?? this.volume,
    errorMessage: clearError ? null : (errorMessage ?? this.errorMessage),
  );
}

/// Ambient noise and completion chime. The focus screen and controller only
/// know this interface; tests use a fake.
abstract class AmbientAudioPlayer {
  ValueListenable<AmbientAudioState> get state;

  /// Chooses the noise colour and starts it looping ([AmbientSound.off]
  /// stops playback).
  Future<void> select(AmbientSound sound);
  Future<void> play();
  Future<void> pause();
  Future<void> setVolume(double volume);

  /// Plays the short completion bell.
  Future<void> playChime();
  Future<void> dispose();
}

class _WavSource extends StreamAudioSource {
  _WavSource(this._bytes);

  final Uint8List _bytes;

  @override
  Future<StreamAudioResponse> request([int? start, int? end]) async {
    final from = start ?? 0;
    final to = end ?? _bytes.length;
    return StreamAudioResponse(
      sourceLength: _bytes.length,
      contentLength: to - from,
      offset: from,
      stream: Stream.value(_bytes.sublist(from, to)),
      contentType: 'audio/wav',
    );
  }
}

/// [AmbientAudioPlayer] using `just_audio` with generated WAV data, so it
/// works offline and on web. Players are created lazily and every failure is
/// reported through [state] instead of thrown.
class JustAudioAmbientPlayer implements AmbientAudioPlayer {
  final _state = ValueNotifier(const AmbientAudioState());
  final _cache = <NoiseType, Uint8List>{};
  AudioPlayer? _ambient;
  AudioPlayer? _chime;
  Uint8List? _chimeBytes;

  @override
  ValueListenable<AmbientAudioState> get state => _state;

  AudioPlayer get _ambientPlayer => _ambient ??= AudioPlayer();

  NoiseType? _typeOf(AmbientSound s) => switch (s) {
    AmbientSound.white => NoiseType.white,
    AmbientSound.pink => NoiseType.pink,
    AmbientSound.brown => NoiseType.brown,
    AmbientSound.off => null,
  };

  @override
  Future<void> select(AmbientSound sound) async {
    final type = _typeOf(sound);
    if (type == null) {
      _state.value = _state.value.copyWith(
        sound: sound,
        isPlaying: false,
        clearError: true,
      );
      try {
        await _ambient?.stop();
      } catch (_) {}
      return;
    }
    try {
      final bytes = _cache[type] ??= NoiseGenerator.noiseWav(type);
      final player = _ambientPlayer;
      await player.setAudioSource(_WavSource(bytes));
      await player.setLoopMode(LoopMode.one);
      await player.setVolume(_state.value.volume);
      _state.value = _state.value.copyWith(
        sound: sound,
        isPlaying: true,
        clearError: true,
      );
      // play() completes when playback ends, so it is not awaited.
      unawaited(player.play().catchError((_) {}));
    } catch (_) {
      _state.value = _state.value.copyWith(
        sound: sound,
        isPlaying: false,
        errorMessage: 'Audio is not available on this device.',
      );
    }
  }

  @override
  Future<void> play() async {
    if (_state.value.sound == AmbientSound.off) return;
    try {
      _state.value = _state.value.copyWith(isPlaying: true);
      unawaited(_ambientPlayer.play().catchError((_) {}));
    } catch (_) {}
  }

  @override
  Future<void> pause() async {
    try {
      await _ambient?.pause();
    } catch (_) {}
    _state.value = _state.value.copyWith(isPlaying: false);
  }

  @override
  Future<void> setVolume(double volume) async {
    final v = volume.clamp(0.0, 1.0);
    _state.value = _state.value.copyWith(volume: v);
    try {
      await _ambient?.setVolume(v);
    } catch (_) {}
  }

  @override
  Future<void> playChime() async {
    try {
      final bytes = _chimeBytes ??= NoiseGenerator.chimeWav();
      final player = _chime ??= AudioPlayer();
      await player.setAudioSource(_WavSource(bytes));
      await player.setVolume(1);
      unawaited(player.play().catchError((_) {}));
    } catch (_) {}
  }

  @override
  Future<void> dispose() async {
    try {
      await _ambient?.dispose();
      await _chime?.dispose();
    } catch (_) {}
    _state.dispose();
  }
}
