// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcVYnS5djj1W7p2SJGpogjALRkGZC3cDY',
    appId: '1:778334231790:web:aaf25206c0e9cc8158e7ff',
    messagingSenderId: '778334231790',
    projectId: 'gen-lang-client-0609884187',
    authDomain: 'gen-lang-client-0609884187.firebaseapp.com',
    databaseURL: 'https://gen-lang-client-0609884187-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gen-lang-client-0609884187.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwHw-btr0w5oYT170hmnGWByWuu4EtlI',
    appId: '1:778334231790:android:18de4b8be93f1f6158e7ff',
    messagingSenderId: '778334231790',
    projectId: 'gen-lang-client-0609884187',
    databaseURL: 'https://gen-lang-client-0609884187-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gen-lang-client-0609884187.firebasestorage.app',
  );
}
