import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Initializes Firebase for the current platform.
///
/// This is intentionally kept separate from `main()`/UI code so startup
/// failures (e.g. missing native configuration) can be handled in one
/// place instead of crashing the whole app.
///
/// Returns `true` if Firebase initialized successfully, `false` otherwise.
/// A `false` result means Firebase-backed features are unavailable until
/// the native configuration (`android/app/google-services.json`, and/or
/// `lib/firebase_options.dart` generated by the FlutterFire CLI) is added
/// — see docs/firebase-setup.md.
Future<bool> initializeFirebase() async {
  try {
    await Firebase.initializeApp();
    return true;
  } catch (error, stackTrace) {
    debugPrint('Firebase initialization failed: $error');
    debugPrintStack(stackTrace: stackTrace);
    return false;
  }
}
